### ISSUE TITLE
stuck on apple logo not even progress bar showing

### ISSUE THREAD

**Issue by UsetUset2244** [AuthenTiiq/authentiiq-ryzen-hackintosh#2]

**Comment by AuthenTiiq** [comment]
in your config.plist add "-v"  in boot-arg to see where it's stuck

**Comment by UsetUset2244** [comment]
the famous error [Boot Stuck on [EB|#LOG:EXITBS:START] @AuthenTiiq

**Comment by tditheo** [comment]
J'ai le même problème chez moi (j'ai essayé avec le guide Dortania ça n'a rien changé)

**Comment by tditheo** [comment]
J’en profite pour savoir quels sont tes résultats sur Heaven Benchmark car ma RX 6600 obtient que 1900 alors que sur Windows j’ai 2800 (ça n’a aucun rapport je sais 😅) @AuthenTiiq

**Comment by AuthenTiiq** [comment]
Vous avez utilisez qu'elle version de MacOS ?
avec qu'elle CPU précisement ?



> J’en profite pour savoir quels sont tes résultats sur Heaven Benchmark car ma RX 6600 obtient que 1900 alors que sur Windows j’ai 2800 (ça n’a aucun rapport je sais 😅) @AuthenTiiq

Alors je n'ai pas fait de Heaven Benchmark, mais du Geekbench.
Je vous donne une comparaison sur Geekbench 5 entre Windows 11 et MacOS 12 : https://browser.geekbench.com/v5/compute/compare/6421289?baseline=6163693

Il faut savoir que généralement sur MacOS les performances sont toujours un peu dessous sur les hackintosh.

**Comment by UsetUset2244** [comment]
pouvez-vous m'aider à résoudre le problème ci-dessus @AuthenTiiq

**Comment by tditheo** [comment]
> Vous avez utilisez qu'elle version de MacOS ? avec qu'elle CPU précisement 
>
J’utilise la dernière version de macOS 13.3.1 et j’ai un Ryzen 5 5500

> Il faut savoir que généralement sur MacOS les performances sont toujours un peu dessous sur les hackintosh.

Évidemment, c’est logique, mais en demandant de l’aide sur Reddit, quelqu’un obtenait un meilleur score que moi sur Heaven avec un GPU plus ancien. Donc je ne sais pas trop pourquoi le miens est plus lent (et je ne suis pas actuellement chez moi pour faire un Geekbench)

**Comment by AuthenTiiq** [comment]
> > Vous avez utilisez qu'elle version de MacOS ? avec qu'elle CPU précisement
> 
> J’utilise la dernière version de macOS 13.3.1 et j’ai un Ryzen 5 5500
> 
> > Il faut savoir que généralement sur MacOS les performances sont toujours un peu dessous sur les hackintosh.
> 
> Évidemment, c’est logique, mais en demandant de l’aide sur Reddit, quelqu’un obtenait un meilleur score que moi sur Heaven avec un GPU plus ancien. Donc je ne sais pas trop pourquoi le miens est plus lent (et je ne suis pas actuellement chez moi pour faire un Geekbench)

Je pense savoir d'ou cela vient, il y a un patch pour les AMD RX dans le config plist qui m'avait permis de booster les performances de mon côté il faudrait que je retrouve cela.

**Comment by AuthenTiiq** [comment]
> pouvez-vous m'aider à résoudre le problème ci-dessus @AuthenTiiq

Oui, dites-moi qu'elle est votre CPU, carte mère et la version MacOS que vous tentez d'utiliser.

Puis si vous utilisez mon EFI je viens de le mettre à jour, réessayez avec celui-ci

**Comment by tditheo** [comment]
> Je pense savoir d'ou cela vient, il y a un patch pour les AMD RX dans le config plist qui m'avait permis de booster les performances de mon côté il faudrait que je retrouve cela.

Je crois qu’il y avait quelque chose avec ATY@ je sais plus trop mais ça avait rien changé

**Comment by AuthenTiiq** [comment]
> > Je pense savoir d'ou cela vient, il y a un patch pour les AMD RX dans le config plist qui m'avait permis de booster les performances de mon côté il faudrait que je retrouve cela.
> 
> Je crois qu’il y avait quelque chose avec ATY@ je sais plus trop mais ça avait rien changé

Je suis en train de faire un Heaven Benchmark en extreme et je vous partagerais mes résultats.

Et non il me semble pas que c’était les patch ATY, ils sont trop vieux et ne fonctionne plus ajd.

**Comment by tditheo** [comment]
> Je suis en train de faire un Heaven Benchmark en extreme et je vous partagerais mes résultats.
> 
> Et non il me semble pas que c’était les patch ATY, ils sont trop vieux et ne fonctionne plus ajd.

D’accord, il me semblais bien que ces patches étaient inutile

**Comment by AuthenTiiq** [comment]
> > Je suis en train de faire un Heaven Benchmark en extreme et je vous partagerais mes résultats.
> > Et non il me semble pas que c’était les patch ATY, ils sont trop vieux et ne fonctionne plus ajd.
> 
> D’accord, il me semblais bien que ces patches étaient inutile

Voila mes résultats 
[
![](https://media.royalcreeps.fr/NucE6/QOYiFoba03.png/raw)
](url)


Pour les patchs GPU j'ai retrouver !

Dans votre config.plist désactiver le patch "algrey - _mtrr_update_action fix PAT - 10.13/10.14/10.15/11.0/12.0/13.0" (Mettez en false)

Puis activer le patch "Shaneee - _mtrr_update_action fix PAT - 10.13/10.14/10.15/11.0/12.0/13.0"

Le patch de Shaneee est plus performant pour le GPU.

**Comment by tditheo** [comment]
> Le patch de Shaneee est plus performant pour le GPU.

Vos résultats sont meilleurs que les miens, cependant j’ai déjà activé ce patch depuis longtemps et ça n’a rien changé

**Comment by AuthenTiiq** [comment]
> 
> Vos résultats sont meilleurs que les miens, cependant j’ai déjà activé ce patch depuis longtemps et ça n’a rien changé

C'est étrange dans ce cas :/ Moi le patch shaneee m'avait grandement améliorer les performances GPU dans MacOS.

Si un jour vous partagez votre EFI je serais curieux de le voir, c'est étrange que ça ne fonctionne pas correctement pour vous.

**Comment by tditheo** [comment]
Je vous le partagerais quand je serais chez moi (fin d’après-midi / ce soir) @AuthenTiiq

**Comment by UsetUset2244** [comment]
my cpu is amd 5600h laptop macos ventura essayé cet efi ça ne marche toujours pas

**Comment by UsetUset2244** [comment]
si quelqu'un peut corriger le bug plz help

**Comment by tditheo** [comment]
> Si un jour vous partagez votre EFI je serais curieux de le voir, c'est étrange que ça ne fonctionne pas correctement pour vous.

Et le voici enfin : [OC.zip](https://github.com/AuthenTiiq/authentiiq-ryzen-hackintosh/files/11359945/OC.zip)

J'ai essayé avec d'autres EFI d'ailleurs, ça ne change pas les résultats

**Comment by tditheo** [comment]
> si quelqu'un peut corriger le bug plz help

Avez-vous essayé [ceci](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start) ?

**Comment by UsetUset2244** [comment]
je n'ai pas compris cette page mais je vais essayer votre oc @tditheo

**Comment by UsetUset2244** [comment]
@tditheo il démarre enfin mais cette erreur se produit

**Comment by UsetUset2244** [comment]
![4](https://user-images.githubusercontent.com/110706082/235322399-cb70c961-d518-4567-8b24-10b93653c97a.jpg)

**Comment by tditheo** [comment]
> @tditheo il démarre enfin mais cette erreur se produit

Je viens de voir que vous avez un Ryzen 5000, est-ce que vous utilisez le GPU intégré ? Sinon quel est votre GPU ?

**Comment by UsetUset2244** [comment]
oui radeon vii

**Comment by UsetUset2244** [comment]
c'est pourquoi dans l'erreur ci-dessus apparaît le mot qui est amd

**Comment by tditheo** [comment]
> oui radeon vii

Je pense que le mieux serait que vous fassiez votre propre EFI à l'aide du guide Dortania (à moins que ça ait déjà été fait) sinon, je ne sais pas d'où pourrait venir cette erreur

**Comment by UsetUset2244** [comment]
oui mais je ne sais pas comment et c'est vraiment difficile avez-vous un tutoriel sur youtube sur la façon de le faire @tditheo

**Comment by tditheo** [comment]
Donnez-moi le modèle précis de votre ordinateur et j'essayerais de créer l'efi pour vous

**Comment by tditheo** [comment]
Avez-vous résolu le problème ? J'ai vu que vous avez fermé le problème @UsetUset2244

**Comment by AuthenTiiq** [comment]
> > Si un jour vous partagez votre EFI je serais curieux de le voir, c'est étrange que ça ne fonctionne pas correctement pour vous.
> 
> Et le voici enfin : [OC.zip](https://github.com/AuthenTiiq/authentiiq-ryzen-hackintosh/files/11359945/OC.zip)
> 
> J'ai essayé avec d'autres EFI d'ailleurs, ça ne change pas les résultats

C'est étrange car votre EFI semble correct vous utilisez les bons patch, à la limite supprimer bien  les patchs ATY@ ils ne servent plus à rien aujourd'hui et ça ne change aucunement les performances et fait même effet inverse pour certains.

Puis y'a t-il une raison spécifique à l'utilisation de AmdTscSync ?

**Comment by AuthenTiiq** [comment]
En effet @UsetUset2244 vous devriez crée votre propre EFI pour votre cas, vous une configuration qui à un certains nombres de différence avec la mienne, ce qui vous causera d'autres problèmes à l'avenir.

Vous pouvez essayer de le faire, prenez votre temps sans vous pressez, surtout si vous n'êtes pas trop habituer, vous risquez de tout mélanger et de vous perdres.

[https://dortania.github.io/OpenCore-Install-Guide/](url)

**Comment by tditheo** [comment]
Je pense simplement que la difference entre nos deux benchmarks sont du au faits que j'étais en 1080p et vous en 900p (ça n'explique toujours pas la différence entre windows et macOS cependant...) @AuthenTiiq

**Comment by AuthenTiiq** [comment]
> Je pense simplement que la difference entre nos deux benchmarks sont du au faits que j'étais en 1080p et vous en 900p (ça n'explique toujours pas la différence entre windows et macOS cependant...) @AuthenTiiq

En effet c'est possible j'ai laisser la résolution par défaut.
Après je sais pas de toute façon y'a tjr une difference entre les deux

**Comment by UsetUset2244** [comment]
ouais je l'ai résolu mais il y a une deuxième erreur là-bas comment puis-je le résoudre je ne sais pas je ne peux pas construire mon propre efi parce que je ne sais pas quel guide suivre @tditheo

**Comment by tditheo** [comment]
> oui radeon vii

Êtes-vous sur que vous avez une radeon vii ? Car c'est une carte graphique de bureau. N'avez vous pas plutôt une Radeon Vega 7 ?

**Comment by UsetUset2244** [comment]
j'ai 5600h les graphiques intérieurs sont vega 7

l'autre carte graphique est 6600m mais j'utilise vega 7 parce que j'ai mux switch @tditheo

**Comment by UsetUset2244** [comment]
c'est un ordinateur portable et une carte de bureau mais dans un ordinateur portable, c'est vega 7 desktop radeon vii
